core/urls.py
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.urls import re_path,path,include
from .import views


app_name = 'core'
urlpatterns = [
    re_path(r'^signup/$', views.Signup.as_view(), name='core-signup'),
    re_path(r'^signup/verify/$', views.SignupVerify.as_view(),
         name='core-signup-verify'),
    re_path(r'signup/resend/verification/link/$',views.ResendVerificationLink.as_view(),
        name="core-signup-resend-verification-link"
        ),

    re_path(r'^login/$', views.Login.as_view(), name='core-login'),
    re_path(r'^refresh/$',TokenRefreshView.as_view(), name='core-refresh'),
    re_path(r'^logout/$', views.Logout.as_view(), name='core-logout'),

    re_path(r'^password/reset/$', views.PasswordReset.as_view(),
         name='core-password-reset'),
    re_path(r'^password/reset/verify/$', views.PasswordResetVerify.as_view(),
         name='core-password-reset-verify'),
    re_path(r'^password/reset/verified/', views.PasswordResetVerified.as_view(),
         name='core-password-reset-verified'),

    re_path(r'^email/change/$', views.EmailChange.as_view(),
         name='core-email-change'),
    re_path(r'^email/change/verify/$', views.EmailChangeVerify.as_view(),
         name='core-email-change-verify'),

    re_path(r'^password/change/$', views.PasswordChange.as_view(),
         name='core-password-change'),

    re_path(r'^users/me/$', views.UserMe.as_view(), name='core-me'),
]

seo_analyzer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('seo/',include('spider.urls', namespace="spider")),
    path('auth/',include('core.urls', namespace='core')),
    path('payment/',include("payment.urls", namespace="payment"))
]

core/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin )
from django.template.loader import render_to_string
from django.core.mail.message import EmailMultiAlternatives
from django.utils.translation import gettext_lazy as _
import binascii
import os
from django.conf import settings
# Create your models here.
# Make part of the model eventually, so it can be edited
EXPIRY_PERIOD = 3    # days


def _generate_code():
    return binascii.hexlify(os.urandom(20)).decode('utf-8')


class UserManager(BaseUserManager):
     
      def create_user(self,email,name=None,password=None,**extra_fields):
          """Create and Save User"""
          if not email:
              raise ValueError('User email is required')
          user = self.model(
              name=name,
              email=self.normalize_email(email)
          )
          
          user.set_password(password)
          user.save()
          return user
      def create_superuser(self,email,password):
          """Create superuser"""
          user = self.create_user(
              email=email,
              password=password
          )
          
          user.is_staff = True
          user.is_superuser = True
          user.is_verified = True
          user.save()
          return user
          
      
      
      


class User(AbstractBaseUser,PermissionsMixin):
      name = models.CharField(max_length=200,null=True,blank=True)
      email = models.EmailField(max_length=200,unique=True)
      is_staff = models.BooleanField(default=False)
      is_active = models.BooleanField(default=True)
      is_superuser = models.BooleanField(default=False)
      is_verified = models.BooleanField(default=False)
      
      USERNAME_FIELD = 'email'
      objects = UserManager()      
      
      def __str__(self):
          return str(self.email)

   

class SignupCodeManager(models.Manager):
    def create_signup_code(self, user, ipaddr):
        code = _generate_code()
        signup_code = self.create(user=user, code=code, ipaddr=ipaddr)

        return signup_code

    def set_user_is_verified(self, code):
        try:
            signup_code = SignupCode.objects.get(code=code)
            signup_code.user.is_verified = True
            signup_code.user.save()
            return True
        except SignupCode.DoesNotExist:
            pass

        return False


class PasswordResetCodeManager(models.Manager):
    def create_password_reset_code(self, user):
        code = _generate_code()
        password_reset_code = self.create(user=user, code=code)

        return password_reset_code

    def get_expiry_period(self):
        return EXPIRY_PERIOD


class EmailChangeCodeManager(models.Manager):
    def create_email_change_code(self, user, email):
        code = _generate_code()
        email_change_code = self.create(user=user, code=code, email=email)

        return email_change_code

    def get_expiry_period(self):
        return EXPIRY_PERIOD


def send_multi_format_email(template_prefix, template_ctxt, target_email):
  
    subject_file = 'core/%s_subject.txt' % template_prefix
    txt_file = 'core/%s.txt' % template_prefix
    html_file = 'core/%s.html' % template_prefix
  
  
    subject = render_to_string(subject_file).strip()
    from_email = settings.EMAIL_HOST_USER
    to = target_email
    # bcc_email = settings.EMAIL_HOST_USER
    text_content = render_to_string(txt_file, template_ctxt)
    html_content = render_to_string(html_file, template_ctxt)
    msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
    msg.attach_alternative(html_content, 'text/html')
    msg.send()


class AbstractBaseCode(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    code = models.CharField(_('code'), max_length=40, primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    site_url = settings.SITE_URL
    class Meta:
        abstract = True

    def send_email(self, prefix):
        ctxt = {
            'email': self.user.email,
            'name':self.user.name,
            'code': self.code,
            'site_url':self.site_url
        }
        send_multi_format_email(prefix, ctxt, target_email=self.user.email)

    def __str__(self):
        return self.code


class SignupCode(AbstractBaseCode):
    ipaddr = models.GenericIPAddressField(_('ip address'))

    objects = SignupCodeManager()

    def send_signup_email(self):
        prefix = 'signup_email'
        self.send_email(prefix)


class PasswordResetCode(AbstractBaseCode):
    objects = PasswordResetCodeManager()

    def send_password_reset_email(self):
        prefix = 'password_reset_email'
        self.send_email(prefix)


class EmailChangeCode(AbstractBaseCode):
    email = models.EmailField(_('email address'), max_length=255)

    objects = EmailChangeCodeManager()

    def send_email_change_emails(self):
        prefix = 'email_change_notify_previous_email'
        self.send_email(prefix)

        prefix = 'email_change_confirm_new_email'
        ctxt = {
            'email': self.email,
            'code': self.code
        }

        send_multi_format_email(prefix, ctxt, target_email=self.email)

core/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from .serializers import (
    UserSerializer,
    SignupSerializer,
    LoginSerializer,
    LogoutSerializer,
    EmailChangeSerializer,
    EmailChangeVerifySerializer,
    PasswordChangeSerializer,
    PasswordResetSerializer,
    PasswordResetVerifiedSerializer,
)
from django.contrib.auth import authenticate
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework import status
from django.utils.translation import gettext as _
from .utils import get_access_token, send_verification_mail
from rest_framework.permissions import IsAuthenticated, AllowAny
from django.conf import settings
from django.contrib.auth import get_user_model
from .models import (
    SignupCode,
    PasswordResetCode,
    EmailChangeCode,
    send_multi_format_email,
)
from datetime import date
from drf_yasg.utils import swagger_auto_schema
from payment.utils import add_months
from payment.models import Subscription
import datetime

# Create your views here.


class Signup(APIView):
    permission_classes = (AllowAny,)
    serializer_class = SignupSerializer

    @swagger_auto_schema(
        responses={200: SignupSerializer(many=True)}, request_body=SignupSerializer
    )
    def post(self, request, format=None):
        """
        Register new User

        """
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():

            name = serializer.data["name"]
            email = serializer.data["email"]
            password = serializer.data["password"]

            must_validate_email = getattr(settings, "AUTH_EMAIL_VERIFICATION", True)

            try:
                user = get_user_model().objects.get(email=email)

                if user.is_verified:
                    content = {"detail": _("Email address already taken.")}
                    return Response(content, status=status.HTTP_400_BAD_REQUEST)

                try:
                    # Delete old signup codes
                    signup_code = SignupCode.objects.get(user=user)
                    signup_code.delete()
                except SignupCode.DoesNotExist:
                    pass

            except get_user_model().DoesNotExist:

                user = get_user_model().objects.create_user(email=email, name=name)

            # Set user fields provided
            user.set_password(password)
            if not must_validate_email:
                user.is_verified = True
                send_multi_format_email(
                    "welcome_email",
                    {
                        "email": user.email,
                    },
                    target_email=user.email,
                )
            user.save()

            subscription = Subscription.objects.create(
                id=user.email, user=user, valid_to=add_months(datetime.date.today(), 1)
            )

            subscription.save()

            if must_validate_email:
                send_verification_mail(request, user)
            auth_data = get_access_token(email, password)
            content = UserSerializer(user).data
            auth_data["user"] = content
            return Response(auth_data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class SignupVerify(APIView):
    permission_classes = (AllowAny,)
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "core/signup_verify_message.html"

    def get(self, request, format=None):
        """
        Very User Email

        """
        code = request.GET.get("code", "")
        verified = SignupCode.objects.set_user_is_verified(code)

        if verified:
            try:
                signup_code = SignupCode.objects.get(code=code)
                signup_code.delete()
            except SignupCode.DoesNotExist:
                pass
            content = {"success": _("Email address verified.")}
            return Response(content)
        else:
            content = {"detail": _("Unable to verify user.")}
            return Response(content)


class ResendVerificationLink(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, format=None):
        """
        Resend User Verification Link
        """
        try:
            user = get_user_model().objects.get(email=request.user)
            send_verification_mail(request, user)
            return Response(
                {"message": "Verification Linked Sent Successfully"},
                status=status.HTTP_200_OK,
            )
        except get_user_model().DoesNotExist:
            return Response({"error": "Uaer matching query doesn't exist"})


class Login(APIView):
    serializer_class = LoginSerializer

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            email = serializer.data["email"]
            password = serializer.data["password"]
            try:
                user = get_user_model().objects.get(email=email)
                if user.is_active:
                    auth_data = get_access_token(email, password)
                    content = UserSerializer(user).data
                    auth_data["user"] = content
                    return Response(auth_data, status=status.HTTP_200_OK)
                else:
                    content = {"detail": _("User account not active.")}
                    return Response(content, status=status.HTTP_401_UNAUTHORIZED)

            except get_user_model().DoesNotExist:
                content = {"detail": _("Unable to login with provided credentials.")}
                return Response(content, status=status.HTTP_401_UNAUTHORIZED)

        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class Logout(APIView):
    serializer_class = LogoutSerializer
    permission_classes = (IsAuthenticated,)

    @swagger_auto_schema(
        responses={200: LogoutSerializer(many=True)}, request_body=LogoutSerializer
    )
    def post(self, request, format=None):
        """
        Log User Out
        """

        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(status=status.HTTP_204_NO_CONTENT)
        else:
            return Response(serializer.errors)


class PasswordReset(APIView):
    permission_classes = (AllowAny,)
    serializer_class = PasswordResetSerializer

    @swagger_auto_schema(
        responses={200: PasswordResetSerializer(many=True)},
        request_body=PasswordResetSerializer,
    )
    def post(self, request, format=None):
        """
        Reset User Password
        Parameters:
         email
        """
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            email = serializer.data["email"]

            try:
                user = get_user_model().objects.get(email=email)

                # Delete all unused password reset codes
                PasswordResetCode.objects.filter(user=user).delete()

                if user.is_verified and user.is_active:
                    password_reset_code = (
                        PasswordResetCode.objects.create_password_reset_code(user)
                    )
                    password_reset_code.send_password_reset_email()
                    content = {"email": email}
                    return Response(content)

            except get_user_model().DoesNotExist:
                pass

            # Since this is AllowAny, don't give away error.
            content = {"detail": _("Password reset not allowed.")}
            return Response(content, status=status.HTTP_400_BAD_REQUEST)

        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PasswordResetVerify(APIView):
    permission_classes = (AllowAny,)
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "core/password_reset_form.html"

    def get(self, request, format=None):

        """
        Verify if user is verified
        parameters:
          code

        """
        code = request.GET.get("code", "")

        try:
            password_reset_code = PasswordResetCode.objects.get(code=code)

            # Delete password reset code if older than expiry period
            delta = date.today() - password_reset_code.created_at.date()
            if delta.days > PasswordResetCode.objects.get_expiry_period():
                password_reset_code.delete()
                raise PasswordResetCode.DoesNotExist()

            content = {"success": _("Email address verified."), "code": code}
            return Response(content)
        except PasswordResetCode.DoesNotExist:
            content = {"detail": _("Unable to verify user.")}
            return Response(content, status=status.HTTP_400_BAD_REQUEST)


class PasswordResetVerified(APIView):

    permission_classes = (AllowAny,)
    serializer_class = PasswordResetVerifiedSerializer

    @swagger_auto_schema(
        responses={200: PasswordResetVerifiedSerializer(many=True)},
        request_body=PasswordResetVerifiedSerializer,
    )
    def post(self, request, format=None):
        """
        Confirm Reset User Password
        Parameters:
           code
           password
        """
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            code = serializer.data["code"]
            password = serializer.data["password"]

            try:
                password_reset_code = PasswordResetCode.objects.get(code=code)
                password_reset_code.user.set_password(password)
                password_reset_code.user.save()

                # Delete password reset code just used
                password_reset_code.delete()

core/templates/core/email_change_confirm_new_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm New Email Address</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,400;0,700;1,100;1,700;1,800;1,900&display=swap');
      body {
          margin: 0;
          font-family: 'Poppins', sans-serif;
         -webkit-font-smoothing: antialiased;
         -moz-osx-font-smoothing: grayscale;
         scroll-behavior: smooth;
         overflow-x:hidden !important;

          }

    
.form{
  width: 100%;
  margin: auto;
  height: auto;
  background: white;
  border-radius: 20px;
  position: relative;
  padding-top: 0rem !important;
 

}



.form h6{
    font: normal 600 18px 'Poppins';
    text-transform: capitalize;
  }
  
  .form p{
    font: normal 500 12px 'Poppins';
    opacity: .7;
  }


.form .button{
  position: relative !important;
  height: 60px;
  padding:0rem;
}

.form .button button{
  position: absolute;
  bottom: 0;
  right: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
  width: 90%;
  height: 40px;
  border-radius: 10px;
  font: normal 500 14px 'Poppins';
  text-transform: capitalize;
  cursor: pointer;
  background:#D78415;
  border:1px solid #D78415;
  color: white;
 
}





</style>
</head>
<body>
    <div class="form shadow">
   
        <h6>Cinfirm Email!</h6>
        <p>Click on button or link to confirm new email</p>
    
    <div class="button">
        <div class="button">
            <a href="{{site_url}}/auth/email/change/verify/?code={{ code }}"> 
                <button class="login-button" style=" left:0%;transform:translate(0%,-50%);" >
                  Confirm
                </button>
            </a>
            
              
                </div>
                <p>
                    Confirm your new email address by clicking on this link:<br>
                    <a href="{{site_url}}/auth/email/change/verify/?code={{ code }}">  {{site_url}}/auth/email/change/verify/?code={{ code }}</a>
                    </p>
  
    </div>
</body>
</html>

core/templates/core/email_change_notify_previous_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account Verified</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,400;0,700;1,100;1,700;1,800;1,900&display=swap');
      body {
          margin: 0;
          font-family: 'Poppins', sans-serif;
         -webkit-font-smoothing: antialiased;
         -moz-osx-font-smoothing: grayscale;
         scroll-behavior: smooth;
         overflow-x:hidden !important;

          }


     
  
.form{
  width: 100%;
  margin: auto;
  height: auto;
  background: white;
  margin-top: 4rem;
  border-radius: 20px;
  position: relative;
  padding-top: 0rem !important;
 

}



.form h6{
    font: normal 600 18px 'Poppins';
    text-transform: capitalize;
  }
  
  .form p{
    font: normal 500 12px 'Poppins';
    opacity: .7;
  }









</style>
</head>
<body>
    <div class="form shadow">
   
        <p>
            A request has been made to change the email address on your account.<br>
            The email address will be changed, if confirmed.
            </p>
    
        </div>
</body>
</html>

core/templates/core/email_changed_message.html
{% extends 'base.html' %}


{% block 'content' %}
<form action="" class="form shadow">
    <h6>Account Verified!</h6>
    <p>
        Your account has been verified successfuly !
    </p>
</form>

{% endblock 'content' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account Verified</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,400;0,700;1,100;1,700;1,800;1,900&display=swap');
      body {
          margin: 0;
          font-family: 'Poppins', sans-serif;
         -webkit-font-smoothing: antialiased;
         -moz-osx-font-smoothing: grayscale;
         scroll-behavior: smooth;
         overflow-x:hidden !important;

          }

    
  
.form{
 width: 100%;
  margin: auto;
  height: auto;
  background: white;
  margin-top: 4rem;
  border-radius: 20px;
  position: relative;
  padding-top: 0rem !important;
 

}



.form h6{
  font: normal 600 18px 'Poppins';
  text-transform: capitalize;
}

.form p{
  font: normal 500 12px 'Poppins';
  opacity: .7;
}









</style>
</head>
<body>
    <div class="form shadow">
   
        
       
        {% if sucess %}
        <h6>Email Changed!</h6>
        <p>
        {sucess}
        </p>
        {%else%}
        <h6>Error Changing Email!</h6>
        <p>
        {detaiil}
    </p>
        {% endif %}
      
    </div>
</body>
</html>

core/templates/core/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Your Password</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,400;0,700;1,100;1,700;1,800;1,900&display=swap');
      body {
          margin: 0;
          font-family: 'Poppins', sans-serif;
         -webkit-font-smoothing: antialiased;
         -moz-osx-font-smoothing: grayscale;
         scroll-behavior: smooth;
         overflow-x:hidden !important;

          }

      :root{
       --red:#D00000;
       --pink:#E5BBBB;
       --primary-font:'Poppins';
       --primary-color:rgba(215, 132, 21, 0.46);
       --secondary-color:#D78415;
       --tertiary-color:#559463;
           }
     
  
.form{
  width: 100%;
  margin: auto;
  height: auto;
  background: white;
  margin-top: 4rem;
  border-radius: 20px;
  position: relative;
  padding-top: 0rem !important;
 

}



.form h6{
    font: normal 600 18px 'Poppins';
    text-transform: capitalize;
  }
  
  .form p{
    font: normal 500 12px 'Poppins';
    opacity: .7;
  }


.form .button{
  position: relative !important;
  height: 60px;
  padding:0rem;
}

.form .button button{
  position: absolute;
  bottom: 0;
  right: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
  width: 90%;
  height: 40px;
  border-radius: 10px;
  font: normal 500 14px 'Poppins';
  text-transform: capitalize;
  cursor: pointer;
  background:#D78415;
  border:1px solid #D78415;
  color: white;
 
}





</style>
</head>
<body>
    <div class="form shadow">
        <h6>Reset Your password!</h6>
        <p>Click on button or link to reset password</p>
        
        <div class="button">
        <a href="{{site_url}}/auth/password/reset/verify/?code={{ code }}">
        <button class="login-button" style=" left:0%;transform:translate(0%,-50%);" >
            Verify Account
        </button>
    </a>
    
      
        </div>
        <p>
            Reset your password by clicking on this link:<br>
            <a href="{{site_url}}/auth/password/reset/verify/?code={{ code }}">{{site_url}}/auth/password/reset/verify/?code={{ code }}</a>
            </p>
    </div>
</body>
</html>

core/templates/core/password_reset_form.html
{% extends 'base.html' %}

{% block 'title' %}
password Reset

{% endblock 'title' %}
{% block 'content' %}






<form class="form shadow">
    {% if success %}
    <h6 id='password-change-success' style="display: none;">
        Password Changed Successfully !
    </h6>
    <div id="password-form">
    <h6>Hello!</h6>
    <p>Create New Password</p>
    <input type="hidden" name="" value="{{code}}" id="code">
    <div class="input" key={elem.id}>
        <div class="row" style='padding:0rem'>
            <div class="col-1 icon">
               <!-- icon -->
               <i class="fa fa-lock" aria-hidden="true"></i>
            </div>
            <div class="col-11">
                <label>Password</label>
                <input
                id="password"
                 type='password'
                 placeholder='passworrd'
               
                 />
            </div>
            
        </div>
      
    </div>
    <div class="input" key={elem.id}>
        <div class="row" style='padding:0rem'>
            <div class="col-1 icon">
               <!-- icon -->
               <i class="fa fa-lock" aria-hidden="true"></i>
            </div>
            <div class="col-11">
                <label>Confirm Password</label>
                <input
                id="confirm_password"
                 type='password'
                 placeholder='passworrd'
               
                 />
            </div>
            
        </div>
    </div>
    <div id="password-errors" class="errors">
        <p class='error'>This field is required !</p>
    </div>
    <div class="errors" id='pc-errors' style="display: none;">
       
    </div>
    <div class="button">
   
    <button class="login-button" id="save_passsword" >
        Save password
    </button>
    <span id="saving-password" style="display: none;">saving password...</span>
    </div>
     
    </div>
   <div class="line"></div>
   {%else%}
<form action="" class="form shadow">
    <p>
        {{detail}}
    </p>
</form>

{% endif %}
</form>



<script>
    $(document).ready(function(){
        $('#save_password').click(function(event){

           
            event.preventDefault();
            // 
            $('#password-error').fadeOut(0);
            $('#verify-error').fadeOut(0);
            $('#pc-errors').fadeOut(0);

            $(this).fadeOut(0,function(){
                $('#saving-password').fadeIn();
            })
            const password = $('#password').val();
            const confirm_password = $('#confirm_password').val();
            const code = $('#code').val();
          

            if(!password){
              $('#password-error').fadeIn(0);
              $('#saving-password').fadeOut(0,function(){
                        $('#save_password').fadeIn();
                    })
              return false;
            }
            if(password!=confirm_password){
                let errors =  $('#pc-errors')
               errors.empty();
               errors.append("<p class='error'>Password and Confirm Password doesn't match</p>");
               errors.fadeIn(0);
               $('#saving-password').fadeOut(0,function(){
                        $('#save_password').fadeIn();
                    })
               return false;


            }
            const data = {
                "code":code.toString(),
                "password":password
            }
            $.ajax({
                url:'{% url "core:core-password-reset-verified" %}',
                type:'POST',
                data:JSON.stringify(data),
                contentType:'application/json',
                success:function(response){
                
    
                   $('#password-form').fadeOut(0,function(){
                       $('#password-change-success').fadeIn(0);
                   })
                
                },
                error:function(errors){
                    $('#verify-error').empty();
                    $('#verify-error').append(errors.responseJSON)
                    $('#verify-error').fadeIn();
                    $('#saving-password').fadeOut(0,function(){
                        $('#save_password').fadeIn();
                    })
                }

            })

            


        })
    })
</script>
{% endblock 'content' %}

core/templates/core/signup_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thank you for signing up!</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,400;0,700;1,100;1,700;1,800;1,900&display=swap');
      body {
          margin: 0;
          font-family: 'Poppins', sans-serif;
         -webkit-font-smoothing: antialiased;
         -moz-osx-font-smoothing: grayscale;
         scroll-behavior: smooth;
         overflow-x:hidden !important;

          }

     
     
  
.form{
  width: 100%;
  margin: auto;
  height: auto;
  background: white;
  margin-top: 4rem;
  border-radius: 20px;
  position: relative;
  padding-top: 0rem !important;
 

}


.form h6{
  font: normal 600 18px 'Poppins';
  text-transform: capitalize;
}

.form p{
  font: normal 500 12px 'Poppins';
  opacity: .7;
}


.form .button{
  position: relative !important;
  height: 60px;
  padding:0rem;
}

.form .button button{
  position: absolute;
  bottom: 0;
  right: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
  width: 90%;
  height: 40px;
  border-radius: 10px;
  font: normal 500 14px 'Poppins';
  text-transform: capitalize;
  cursor: pointer;
  background:#D78415;
  border:1px solid #D78415;
  color: white;
 
}





</style>
</head>
<body>
    <form class="form shadow">
   
    <h6>Verify Account!</h6>
    <p>Click on button or link to verify your account</p>
    
    <div class="button">
   <a href="{{site_url}}/auth/signup/verify/?code={{ code }}">
    <button class="login-button" style=" left:0%;transform:translate(0%,-50%);" >
        Verify Account
    </button>
    </a>
  
    </div>
    <p>
        Verify your email address by clicking on this link:<br>
        <a href="{{site_url}}/auth/signup/verify/?code={{ code }}">{{site_url}}/auth/signup/verify/?code={{ code }}</a>
        </p>
  
    </form>
</body>
</html>